services:  
  azure-cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    ports:
      - "8081:8081"
      - "10250-10255:10250-10255"
    environment:
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: "127.0.0.1"
    volumes:
      - ./cosmosdb-data:/data
    healthcheck:
      test: curl -f https://localhost:8081/_explorer/index.html || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 1s