name: Main Branch Push Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Docker Compose
      run: |
        docker compose up -d --remove-orphans

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Install Cosmos Certificate
      run: |
        curl -k https://localhost:8081/_explorer/emulator.pem > ~/emulatorcert.crt
        sudo cp ~/emulatorcert.crt /usr/local/share/ca-certificates/
        sudo update-ca-certificates

    - name: Test
      run: dotnet test

    - name: Tidy up
      if: always()
      run: |
        docker compose logs
        docker compose down